apiVersion: apps/v1
kind: Deployment
metadata:
  name: ReaderExperience
  labels:
    app: ReaderExperience
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ReaderExperience
  template:
    metadata:
      labels:
        app: ReaderExperience
    spec:
      containers:
        - name: ReaderExperience
          image: "username/ReaderExperience:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
