apiVersion: v1
kind: Service
metadata:
  name: AdminServiceOperation
  labels:
    app: AdminServiceOperation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: AdminServiceOperation