apiVersion: v1
kind: Service
metadata:
  name: AuthorWorksManagement
  labels:
    app: AuthorWorksManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: AuthorWorksManagement