---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: AuthorWorksManagement
  labels:
    app: AuthorWorksManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuthorWorksManagement
  template:
    metadata:
      labels:
        app: AuthorWorksManagement
    spec:
      containers:
        - name: AuthorWorksManagement
          image: username/AuthorWorksManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ReaderExperience
  labels:
    app: ReaderExperience
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ReaderExperience
  template:
    metadata:
      labels:
        app: ReaderExperience
    spec:
      containers:
        - name: ReaderExperience
          image: username/ReaderExperience:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: AdminServiceOperation
  labels:
    app: AdminServiceOperation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AdminServiceOperation
  template:
    metadata:
      labels:
        app: AdminServiceOperation
    spec:
      containers:
        - name: AdminServiceOperation
          image: username/AdminServiceOperation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: AuthorWorksManagement
  labels:
    app: AuthorWorksManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: AuthorWorksManagement


---


apiVersion: v1
kind: Service
metadata:
  name: ReaderExperience
  labels:
    app: ReaderExperience
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ReaderExperience


---


apiVersion: v1
kind: Service
metadata:
  name: AdminServiceOperation
  labels:
    app: AdminServiceOperation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: AdminServiceOperation

